/**
 * AutoTrack — Central Expense Category Constants
 * Single source of truth for all category definitions.
 * Import this wherever categories are needed to ensure consistency.
 */

export const CATEGORY_KEYS = {
  FUEL: 'Fuel',
  MAINTENANCE: 'Maintenance',
  TOLL: 'Toll',
  COMPLIANCE: 'Compliance',
  DEPRECIATION: 'Depreciation',
  INSURANCE: 'Insurance',
  FIRE_SAFETY_IT: 'Fire_Safety_IT_Infra',
}

export const EXPENSE_CATEGORIES = [
  {
    key: CATEGORY_KEYS.FUEL,
    label: 'Fuel',
    icon: '⛽',
    color: 'bg-yellow-500/10 text-yellow-500',
    chartColor: '#f7c948',
    subcategories: ['Petrol 95', 'Petrol 98', 'Diesel', 'Electric Charge', 'Other'],
    vatApplicable: true,
  },
  {
    key: CATEGORY_KEYS.MAINTENANCE,
    label: 'Maintenance',
    icon: '🔧',
    color: 'bg-blue-600/10 text-blue-400',
    chartColor: '#6c63ff',
    subcategories: ['Oil & Filter', 'Brakes', 'Battery', 'Tyres', 'A/C Service', 'Suspension', 'Transmission', 'Body Repair', 'Other'],
    vatApplicable: true,
  },
  {
    key: CATEGORY_KEYS.TOLL,
    label: 'Toll',
    icon: '🛣️',
    color: 'bg-teal-500/10 text-teal-400',
    chartColor: '#3ecf8e',
    subcategories: ['Salik', 'Darb', 'Aber', 'Other Gate'],
    vatApplicable: false,
  },
  {
    key: CATEGORY_KEYS.COMPLIANCE,
    label: 'Compliance',
    icon: '📋',
    color: 'bg-indigo-500/10 text-indigo-400',
    chartColor: '#818cf8',
    subcategories: ['Vehicle Registration', 'RTA Inspection', 'Mulkiya Renewal', 'Traffic Fine', 'Other'],
    vatApplicable: true,
  },
  {
    key: CATEGORY_KEYS.DEPRECIATION,
    label: 'Depreciation',
    icon: '📉',
    color: 'bg-slate-500/10 text-slate-400',
    chartColor: '#94a3b8',
    subcategories: ['Monthly Auto-Generated'],
    vatApplicable: false,
    autoGenerated: true,
  },
  {
    key: CATEGORY_KEYS.INSURANCE,
    label: 'Insurance',
    icon: '🛡️',
    color: 'bg-green-500/10 text-green-400',
    chartColor: '#4ade80',
    subcategories: ['Comprehensive', 'Third Party', 'GAP Insurance', 'Other'],
    vatApplicable: true,
  },
  {
    key: CATEGORY_KEYS.FIRE_SAFETY_IT,
    label: 'Fire & Safety and IT & Camera Infrastructure',
    icon: '🛡️',
    color: 'bg-orange-500/10 text-orange-400',
    chartColor: '#fb923c',
    subcategories: [
      'Fire extinguisher purchase',
      'Fire extinguisher refill/service',
      'First aid / safety kit',
      'Reflective triangles / cones / warning devices',
      'Vehicle emergency tools',
      'Dash camera',
      'Reverse camera',
      'Cabin camera',
      'GPS / telematics camera hardware',
      'DVR / NVR / storage device',
      'SIM / connectivity for camera unit',
      'Camera wiring / installation',
      'Camera repair / replacement',
      'Monitoring software / licensing',
      'Other fire & safety / IT / camera cost',
    ],
    vatApplicable: true,
  },
]

/**
 * Returns a category definition object by its key.
 * Falls back gracefully for unknown categories (backward compat).
 */
export function getCategoryByKey(key) {
  return (
    EXPENSE_CATEGORIES.find((c) => c.key === key) ?? {
      key,
      label: key,
      icon: '📦',
      color: 'bg-white/10 text-white/60',
      chartColor: '#8890a8',
      subcategories: ['Other'],
      vatApplicable: false,
    }
  )
}

/**
 * All filter tab options — "All" prepended.
 */
export const FILTER_TABS = [
  { name: 'All', icon: 'filter' },
  ...EXPENSE_CATEGORIES.map((c) => ({ name: c.key, emoji: c.icon })),
]
